services:
  mt5:
    build: .
    container_name: mt5
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    environment:
      - MT5_COUNT=${MT5_COUNT:-1}
    env_file:
      - .env

